name: Update this repo's BLOG POSTS

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed-url: https://evotec.xyz/feed/
          max_post_count: 10
          comment_tag_name: BLOG-POST-LIST